### ISSUE TITLE
Support for Material MkDocs features

### ISSUE THREAD

**Issue by mycroftsnm** [flynneva/mkdocs-custom-superfence-example#1]
Hi! 
I noticed when i use the prefix, all of the Material Theme features don't work
For example:
```
    ```{.prefix prefix="$" title="Checking memory use"}
    free -h 
    ```
```
Do not show the title "Checking memory use"

Also features like  [Code Anotattions](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations) don̈́t work

**Comment by flynneva** [comment]
@mycroftsnm good catch! I'll check back on this on Friday to see if I can edit the formatting a bit to make those features still work. It should be possible I think.

**Comment by flynneva** [comment]
@mycroftsnm I just rewrote the custom superfence to be way more flexible, and now it can be used as a general "add-on" to any fence I think 😄 

Seems to be working ok: https://flynneva.github.io/mkdocs-custom-superfence-example/main/

**Comment by mycroftsnm** [comment]
Works flawlessly! Thanks
